### ISSUE TITLE
Difference between CenterNet and CenterNet++

### ISSUE THREAD

**Issue by trathpai** [Duankaiwen/PyCenterNet#6]
Hi,

What is the main difference between original centernet and centernet++?

**Comment by dat3814606** [comment]
In CenterNet++, they proposed two models, Single resolution detection network (basically the same as CenterNet you know) and Multi resolution detection network.
Multi resolution network replaces hourglass+heatmap+embeddings (single resolution network) with fpn+heatmap+regression. A lot of concepts come with that replacement but the basic idea is like above.

**Comment by trathpai** [comment]
Ok thankyou!
